10.25

In [16]:
len?

In [17]:
L=[1,2,3]

In [18]:
L.insert?


In [19]:
L?


In [20]:
def square(a):
    return a**2



In [21]:
square??


In [22]:
%timeit L=[n**2 for n in range(1000)]

454 µs ± 33.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [23]:
print(In)

['', "get_ipython().magic('pinfo len')", 'L=[1,2,3]', "get_ipython().magic('pinfo L.insert')", "get_ipython().magic('pinfo L')", 'def square(a):\n    return a**2', "get_ipython().magic('pinfo2 square')", "get_ipython().magic('timeit L=[n**2 for n in range(1000)]')", 'print(In)', 'Out', 'import math', 'math.sin(2)', 'print(_)', 'def func1(a,b):\n    return a/b\ndef func2(x):\n    a=x\n    b=x-1\n    return func1(a,b)', 'func2(1)', 'x=np.array([1,2,3])', "get_ipython().magic('pinfo len')", 'L=[1,2,3]', "get_ipython().magic('pinfo L.insert')", "get_ipython().magic('pinfo L')", 'def square(a):\n    return a**2', "get_ipython().magic('pinfo2 square')", "get_ipython().magic('timeit L=[n**2 for n in range(1000)]')", 'print(In)']


In [24]:
Out

{11: 0.9092974268256817}

In [25]:
import math


In [26]:
math.sin(2)

0.9092974268256817

In [27]:
print(_)

0.9092974268256817


In [28]:
def func1(a,b):
    return a/b
def func2(x):
    a=x
    b=x-1
    return func1(a,b)

In [29]:
func2(1)

ZeroDivisionError: division by zero

In [ ]:
%xmode Plain

In [ ]:
func2(1)

In [ ]:
%debug

In [ ]:
import numpy

### 10.29

In [31]:
import numpy as np


In [ ]:
np.random.seed(0)

In [ ]:
x3=np.random.randint(10,size=(3,4,5))

In [ ]:
print(x3.ndim)

In [ ]:
print(x3.shape)

In [ ]:
print(x3.size)

In [ ]:
x1=np.random.randint(10,size=6)

In [ ]:
x2=np.random.randint(10,size=(3,4))

In [ ]:
x1

In [ ]:
x1[0]

In [ ]:
x=np.arange(10)

In [ ]:
x

In [ ]:
x[:5]

In [ ]:
x[4:7]

In [ ]:
x{::2}

In [ ]:
x[::2]

In [ ]:
x[1::2]

In [ ]:
x2

In [ ]:
x2[:2,:3]

In [ ]:
x2[:3,::2]

In [ ]:
x2[::-1,::-1]

In [ ]:
print(x2[:,0])

In [ ]:
print(x2[0,:])

In [ ]:
grid=np.arange(1,10).reshape(3,3)

In [ ]:
grid

In [ ]:
x=np.array([1,2,3])

In [ ]:
x.reshape((1,3))

In [ ]:
x.reshape((3,1))

In [32]:
x=np.array([1,2,3])

In [33]:
y=np.array([3,2,1])

In [34]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [37]:
grid=np.array([[1,2,3],
             [4,5,6]])

In [38]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [39]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [40]:
np.vstack([x,grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [44]:
y=np.array([[1],
           [2],
           ])

In [45]:
np.hstack([grid,y])

array([[1, 2, 3, 1],
       [4, 5, 6, 2]])

In [46]:
x=[1,2,3,99,99,3,2,1]

In [47]:
x1,x2,x3=np.split(x,[3,5])

In [48]:
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [50]:
grid=np.arange(16).reshape((4,4))

In [51]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
upper,lower=np.vsplit(grid,[2])

In [53]:
print(upper)

[[0 1 2 3]
 [4 5 6 7]]


In [54]:
print(lower)

[[ 8  9 10 11]
 [12 13 14 15]]


In [55]:
left,right=np.hsplit(grid,[2])

In [56]:
print(left)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [57]:
print(right)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [58]:
big_array=np.random.randint(1,100,size=1000000)

In [59]:
%timeit(1.0/big_array)

8.97 ms ± 317 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
