10.25

In [1]:
len?

In [2]:
L=[1,2,3]

In [3]:
L.insert?


In [4]:
L?


In [5]:
def square(a):
    return a**2



In [7]:
square??


In [9]:
%timeit L=[n**2 for n in range(1000)]

416 µs ± 7.29 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
Compiler time: 0.28 s


In [10]:
print(In)

['', "get_ipython().magic('pinfo len')", 'L=[1,2,3]', "get_ipython().magic('pinfo L.insert')", "get_ipython().magic('pinfo L')", 'def square(a):\n    return a**2', "get_ipython().magic('pinfo square')", "get_ipython().magic('pinfo2 square')", "get_ipython().run_cell_magic('timeit', 'L=[n**2 for n in range(1000)]', '')", "get_ipython().magic('timeit L=[n**2 for n in range(1000)]')", 'print(In)']


In [15]:
Out

{14: 0.9092974268256817}

In [13]:
import math


In [14]:
math.sin(2)

0.9092974268256817

In [16]:
print(_)

0.9092974268256817


In [17]:
def func1(a,b):
    return a/b
def func2(x):
    a=x
    b=x-1
    return func1(a,b)

In [18]:
func2(1)

ZeroDivisionError: division by zero

In [19]:
%xmode Plain

Exception reporting mode: Plain


In [20]:
func2(1)

ZeroDivisionError: division by zero

In [21]:
%debug

> <ipython-input-17-d2053b33f000>(2)func1()
      1 def func1(a,b):
----> 2     return a/b
      3 def func2(x):
      4     a=x
      5     b=x-1

ipdb> print(a)
1
ipdb> print(b)
0
ipdb> up
> <ipython-input-17-d2053b33f000>(6)func2()
      2     return a/b
      3 def func2(x):
      4     a=x
      5     b=x-1
----> 6     return func1(a,b)

ipdb> up
> <ipython-input-20-b2e110f6fc8f>(1)<module>()
----> 1 func2(1)

ipdb> down
> <ipython-input-17-d2053b33f000>(6)func2()
      2     return a/b
      3 def func2(x):
      4     a=x
      5     b=x-1
----> 6     return func1(a,b)

ipdb> quit


In [ ]:
import numpy

### 10.29

In [1]:
import numpy as np


In [2]:
np.random.seed(0)

In [3]:
x3=np.random.randint(10,size=(3,4,5))

In [4]:
print(x3.ndim)

3


In [5]:
print(x3.shape)

(3, 4, 5)


In [6]:
print(x3.size)

60


In [7]:
x1=np.random.randint(10,size=6)

In [8]:
x2=np.random.randint(10,size=(3,4))

In [9]:
x1

array([8, 1, 1, 7, 9, 9])

In [10]:
x1[0]

8

In [11]:
x=np.arange(10)

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[:5]

array([0, 1, 2, 3, 4])

In [14]:
x[4:7]

array([4, 5, 6])

In [15]:
x{::2}

SyntaxError: invalid syntax (<ipython-input-15-f85b36f0b441>, line 1)

In [16]:
x[::2]

array([0, 2, 4, 6, 8])

In [17]:
x[1::2]

array([1, 3, 5, 7, 9])

In [18]:
x2

array([[3, 6, 7, 2],
       [0, 3, 5, 9],
       [4, 4, 6, 4]])

In [19]:
x2[:2,:3]

array([[3, 6, 7],
       [0, 3, 5]])

In [20]:
x2[:3,::2]

array([[3, 7],
       [0, 5],
       [4, 6]])

In [21]:
x2[::-1,::-1]

array([[4, 6, 4, 4],
       [9, 5, 3, 0],
       [2, 7, 6, 3]])

In [22]:
print(x2[:,0])

[3 0 4]


In [23]:
print(x2[0,:])

[3 6 7 2]


In [25]:
grid=np.arange(1,10).reshape(3,3)

In [26]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
x=np.array([1,2,3])

In [29]:
x.reshape((1,3))

array([[1, 2, 3]])

In [30]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])